# Generated by Django 3.1.4 on 2020-12-09 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentcontract',
            old_name='idClient',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='rentcontract',
            old_name='contractPeriod',
            new_name='leaseEndDate',
        ),
        migrations.AddField(
            model_name='premises',
            name='rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentcontract',
            name='leaseStartDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
